IMAGE_REPO = registry.gitlab.com/modioab/base-image/fedora-28/go

FEDORA_ROOT_ARCHIVE = rootfs.tar
IMAGE_FILES = $(FEDORA_ROOT_ARCHIVE)
FEDORA_ROOT_PACKAGES = make golang git tar docker-common


include ../build.mk
