BASE_IMAGE_TAG ?= master
IMAGE_REPO = registry.gitlab.com/modioab/base-image/fedora-$(FEDORA_ROOT_RELEASE)/jstest
IMAGE_BUILD_FROM = registry.gitlab.com/modioab/base-image/fedora-$(FEDORA_ROOT_RELEASE)/build:$(BASE_IMAGE_TAG)

include ../build.mk
