# This must be hard-coded and keept in sync with the Dockerfile
IMAGE_REPO = $(CI_REGISTRY_IMAGE)/fedora-$(FEDORA_ROOT_RELEASE)/build
IMAGE_BUILD_FROM = $(CI_REGISTRY_IMAGE)/fedora-$(FEDORA_ROOT_RELEASE)/bootstrap:latest

include ../build.mk
