include ../build.mk

IMAGE_REPO = registry.gitlab.com/modioab/base-image
IMAGE_TAG_PREFIX = fedora-$(FEDORA_ROOT_RELEASE)-nginx

FEDORA_ROOT_ARCHIVE = rootfs.tar
IMAGE_FILES += $(FEDORA_ROOT_ARCHIVE)

FEDORA_ROOT_PACKAGES = nginx
